# Generated by Django 6.0.2 on 2026-04-07 17:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=50)),
                ('console', models.CharField(choices=[('ps5', 'Playstation 5'), ('ps4', 'Playstation 4'), ('ps3', 'Playstation 3'), ('ps2', 'Playstation 2'), ('ps1', 'Playstation 1'), ('xsx', 'Xbox Series X'), ('xss', 'Xbox Series S'), ('xb1', 'Xbox One'), ('xb360', 'Xbox 360'), ('xb', 'Xbox'), ('ns2', 'Switch 2'), ('nsw', 'Switch'), ('wiiu', 'Wii U'), ('wii', 'Wii'), ('gcn', 'GameCube'), ('n64', 'Nintendo 64'), ('snes', 'SNES'), ('nes', 'NES'), ('pc', 'PC'), ('other', 'Other')], max_length=30)),
                ('release_year', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2026)])),
                ('genre', models.CharField(choices=[('action', 'Action'), ('action-adventure', 'Action-Adventure'), ('adventure', 'Adventure'), ('horror', 'Horror'), ('party', 'Party'), ('platformer', 'Platformer'), ('puzzle', 'Puzzle'), ('rpg', 'RPG'), ('shooter', 'Shooter'), ('simulation', 'Simulation'), ('sports/racing', 'Sports/Racing'), ('strategy', 'Strategy'), ('other', 'Other')], max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('box_art', models.ImageField(blank=True, null=True, upload_to='game_pics/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
