# Generated by Django 6.0.2 on 2026-03-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='box_art',
            field=models.ImageField(blank=True, null=True, upload_to='game_pics/'),
        ),
    ]
