# Generated by Django 6.0.2 on 2026-04-06 19:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_box_art'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.CharField(choices=[('action', 'Action'), ('action-adventure', 'Action-Adventure'), ('adventure', 'Adventure'), ('horror', 'Horror'), ('party', 'Party'), ('platformer', 'Platformer'), ('puzzle', 'Puzzle'), ('rpg', 'RPG'), ('shooter', 'Shooter'), ('simulation', 'Simulation'), ('sports/racing', 'Sports/Racing'), ('strategy', 'Strategy'), ('other', 'Other')], default='action', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='release_year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2026)]),
        ),
    ]
