# Generated by Django 6.0.2 on 2026-04-08 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gametrackeruser',
            name='profile_picture',
        ),
    ]
